require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'examples/**/*'

Metrics/BlockLength:
  Exclude:
    - 'rack-shield.gemspec'
    - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/NestedGroups:
  Max: 5
