language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler -v 2.0.1
script:
  - bundle exec rspec
  - bundle exec rubocop
