language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - ruby-head

jobs:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  email:
    on_success: never

before_install:
  - gem update --system
  - gem install bundler -v 2.0.1
script:
  - bundle exec rspec
  - bundle exec rubocop
