language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

jobs:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  email:
    on_success: never

branches:
  only:
    - master

git:
  depth: 3
  quiet: true

before_install:
  - yes | gem update --system --force
  - gem install bundler
